version: '3.3'
services:
  zookeeper1:
    image: zlchen/kafka-cluster:0.11
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181"
      - "2888"
      - "3888"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - ZOOKEEPER_myid=1
      - ZOOKEEPER_initLimit=5
      - ZOOKEEPER_syncLimit=2
      - ZOOKEEPER_dataDir=/zookeeper
      - ZOOKEEPER_servers=server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      - RUN=zookeeper
    restart: always

  zookeeper2:
    image: zlchen/kafka-cluster:0.11
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2181"
      - "2888"
      - "3888"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - ZOOKEEPER_myid=2
      - ZOOKEEPER_initLimit=5
      - ZOOKEEPER_syncLimit=2
      - ZOOKEEPER_dataDir=/zookeeper
      - ZOOKEEPER_servers=server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      - RUN=zookeeper
    restart: always

  zookeeper3:
    image: zlchen/kafka-cluster:0.11
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2181"
      - "2888"
      - "3888"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - ZOOKEEPER_myid=3
      - ZOOKEEPER_initLimit=5
      - ZOOKEEPER_syncLimit=2
      - ZOOKEEPER_dataDir=/zookeeper
      - ZOOKEEPER_servers=server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      - RUN=zookeeper
    restart: always

  kafka1:
    image: zlchen/kafka-cluster:0.11
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - KAFKA_broker_id=0
      - KAFKA_listeners=PLAINTEXT://:9092
      - KAFKA_advertised_listeners=PLAINTEXT://kafka1:9092
      - KAFKA_log_dirs=/kafka
      - KAFKA_num_partitions=3
      - KAFKA_delete_topic_enable=true
      - KAFKA_auto_create_topics_enable=true
      - KAFKA_zookeeper_connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - RUN=kafka
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: always

  kafka2:
    image: zlchen/kafka-cluster:0.11
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9092"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - KAFKA_broker_id=1
      - KAFKA_listeners=PLAINTEXT://:9092
      - KAFKA_advertised_listeners=PLAINTEXT://kafka1:9092
      - KAFKA_log_dirs=/kafka
      - KAFKA_num_partitions=3
      - KAFKA_delete_topic_enable=true
      - KAFKA_auto_create_topics_enable=true
      - KAFKA_zookeeper_connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - RUN=kafka
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: always

  kafka3:
    image: zlchen/kafka-cluster:0.11
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9092"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms500M
      - KAFKA_broker_id=2
      - KAFKA_listeners=PLAINTEXT://:9092
      - KAFKA_advertised_listeners=PLAINTEXT://kafka1:9092
      - KAFKA_log_dirs=/kafka
      - KAFKA_num_partitions=3
      - KAFKA_delete_topic_enable=true
      - KAFKA_auto_create_topics_enable=true
      - KAFKA_zookeeper_connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - RUN=kafka
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: always
